### PR TITLE
Add conan support

### PR DESCRIPTION
**Pull request by Lucas-Vertrees-Bose**

### CODE REVIEW

**Comment by Lucas-Vertrees-Bose** [comment]
@Mark-Hatch-Bose There's an issue here where running the qc build scripts from conan versus locally results in different Makefile variables. Locally, `CC= $(CROSS_COMPILE)gcc` and with conan `CC= $(CROSS_COMPILE)-fPIC -mtune=cortex-a53 --sysroot=/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/aarch64-oe-linux`. I added `CC=arm-oemllib32-linux-gcc` when calling make to circumvent this, but if you know a better way let me know.

**Comment by Mark-Hatch-Bose** [comment]
> Locally, `CC= $(CROSS_COMPILE)gcc` and with conan `CC= $(CROSS_COMPILE)-fPIC -mtune=cortex-a53 --sysroot=/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/aarch64-oe-linux`.

Good findings. We aren't setting those compile flags in our profile, so it's likely coming from a `tools-${SDK}` located inside the repo? I'd have to investigate further.

You can see the profile definition here for `qc8017_32` for conan.
https://github.com/BoseCorp/CastleConanConfig/blob/master/profiles/qc8017_32

**Comment by Lucas-Vertrees-Bose** [comment]
I don't like specifying the `CC` before making, as it should be set automatically. Something funky is definitely going on.

**Comment by Lucas-Vertrees-Bose** [comment]
@Michael-Cook-Bose @vignesh-sekarbabu-bose any idea why this error is getting outputted on EF? 
```
make[2]: Entering directory '/scratch/scm/OpenSource-openssl/sandbox4/apps'
( :; LIBDEPS="${LIBDEPS:--L.. -lssl  -L.. -lcrypto -Wl,-R,$ORIGIN/../lib -ldl}"; LDCMD="${LDCMD:-arm-oemllib32-linux-gcc}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -march=armv7-a -mfloat-abi=softfp -mfpu=neon -mtune=cortex-a53 --sysroot=/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/aarch64-oe-linux -O3 -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM}"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=openssl} openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o ${LIBDEPS} )
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: dhparam.o uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file dhparam.o
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: ../libcrypto.a(armcap.o) uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file ../libcrypto.a(armcap.o)
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: ../libcrypto.a(e_gost_err.o) uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file ../libcrypto.a(e_gost_err.o)
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: ../libcrypto.a(gost89.o) uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file ../libcrypto.a(gost89.o)
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: ../libcrypto.a(gosthash.o) uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file ../libcrypto.a(gosthash.o)
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: error: ../libcrypto.a(gost_keywrap.o) uses VFP register arguments, openssl does not
/scratch/components-cache/Release/master/4.10/Riviera-Toolchain/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/4.9.3/real-ld: failed to merge target specific data of file ../libcrypto.a(gost_keywrap.o)
collect2: error: ld returned 1 exit status
```

Running `build-qc8017_32` on my machine locally successfully builds without error.

**Comment by Michael-Cook-Bose** [comment]
You need to make sure you clean your workspace between builds of different sdk's.
That's my first guess.

**Comment by Derek-Richardson-Bose** [comment]
@Michael-Cook-Bose please review

**Pull request merged**
